### ISSUE TITLE
Allow to retrieve condition function result

### ISSUE THREAD

**Issue by rockem** [rockem/busypie#26]
Sometimes I want to do that:
```
message = wait().until(wait_for_message)
assert message.id = '234'
```

**Comment by rockem** [comment]
Implemented

**Comment by darkdragon-001** [comment]
It would be nice if there was an option to also return a `False` result instead of throwing an exception.

**Comment by rockem** [comment]
@darkdragon-001 I agree, You're welcomed to open an issue for that
